### ISSUE TITLE
[🐛 bug] Fix Unauthenticated User Access to Dashboard UI

### ISSUE THREAD

**Issue by qridwan** [qridwan/xNote-FE#31]
### Current Behavior:
Currently, unauthenticated users are able to access the dashboard UI, which poses a security risk and violates access control policies.

### Expected Behavior:
Restrict access to the dashboard UI to authenticated users only. Unauthorized users should be redirected to the login page or shown an appropriate access denied message.

**Comment by SandipGyawali** [comment]
@qridwan is this open to contribute if yes i can work on it.

**Comment by SandipGyawali** [comment]
@qridwan can you assign me the issue ?

**Comment by qridwan** [comment]
> @qridwan can you assign me the issue ?
------
@SandipGyawali Done ✅
