### ISSUE TITLE
[✏️ feature] Introduce Edit Notebook

### ISSUE THREAD

**Issue by qridwan** [qridwan/xNote-FE#33]
### Current State:
Currently, there is no option to modify existing notebook details once they are created.

### Expected Behavior:
Implement a feature that allows users to edit notebook details after creation. This enhancement will provide flexibility and improve user experience by enabling users to update notebook names and descriptions as needed.

<img width="514" alt="image" src="https://github.com/qridwan/xNote-FE/assets/73544823/aaef4530-38fb-4cc2-b4a1-54dda98dfd0e">
<img width="1511" alt="image" src="https://github.com/qridwan/xNote-FE/assets/73544823/35973c11-00a7-4625-9134-b923da72eacc">

**Comment by SandipGyawali** [comment]
@qridwan can i look at it ?

**Comment by qridwan** [comment]
> @qridwan can i look at it ?
> 
> 

Sure please, we have already prepared the BE service ready for integration aswell please, please let me know if there is any doubts you have
